
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        price-in:
          destination: price
          contentType: application/json
        price-out:
          destination: price
          contentType: application/json